# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: _external_build_artifact # identifier for the container resource      
      type: ACR # type of the registry like ACR, GCR etc. 
      azureSubscription: 'Microsoft Azure Internal Consumption (daaeef3e-d7fe-49e8-baaa-b3df9d072825)' # Azure subscription (ARM service connection) for container registry;
      resourceGroup: 'Wicresoft-Support' # resource group for your ACR
      registry: 'gingacr' # registry for container images
      repository: 'gingtest' # name of the container image repository in ACR

stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'TestACR'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'RMDev (c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    appName: 'nodeexpresscontainer'